<?php


namespace Lagumen\Essential\Tests\Feature;

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use Lagumen\Essential\Tests\FeatureTest;

class CommandsTest extends FeatureTest
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_can_generate_validation_class_on_default_namespace()
    {
        $fooClass = app_path('App/Http/Validation/UserValidation.php');

        Artisan::call("make:essential-validation UserValidation");

//        $this->assertTrue(File::exists($fooClass));

//        $this->assertDirectoryExists("App\Http\Validations");
//        $this->assertFileExists("App\Http\Validation\UserValidation.php");
    }
}
