<?php


namespace Lagumen\LaravelEssential\Tests\Feature;


use Illuminate\Foundation\Testing\RefreshDatabase;
use Lagumen\LaravelEssential\Tests\FeatureTest;
use Lagumen\LaravelEssential\Tests\Models\User;

class RepositoriesTest extends FeatureTest
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_can_create_new_user_and_add_setting()
    {
        $this->withoutExceptionHandling();

        $response = $this->postJson(route('users.store'), [
            'name'     => $name = 'Ralph Lagumen',
            'email'    => $email = 'iamralphlagumen@gmail.com',
            'timezone' => $timezone = 'Asia/Manila'
        ])->assertJsonFragment([
            'name'  => $name,
            'email' => $email
        ]);

        $user = json_decode($response->getContent());

        $this->assertDatabaseHas('users', [
            'id'    => $user->id,
            'name'  => $name,
            'email' => $email
        ]);

        $this->assertDatabaseHas('user_settings', [
            'user_id'  => $user->id,
            'timezone' => $timezone
        ]);
    }

    /** @test */
    public function it_can_return_specified_model_by_id()
    {
        $user = factory(User::class)->create();

        $this->getJson(route('users.show', $user->id))
            ->assertJsonFragment([
                'id'    => $user->id,
                'name'  => $user->name,
                'email' => $user->email
            ]);
    }
}
