<?php


namespace Lagumen\LaravelEssential\Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Lagumen\LaravelEssential\Tests\FeatureTest;

class ValidationsTest extends FeatureTest
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function it_can_validate_invalid_request()
    {
        $this->postJson(route('users.store'), [
            'name'  => 'Ralph Lagumen',
            'email' => null
        ])
            ->assertStatus(422)
            ->assertJsonValidationErrors(['email']);
    }
}
